services:
  registry:
    image: hashicorp/consul:1.15
    container_name: registry
    ports:
      - "8500:8500"

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8001:8001"
    depends_on:
      - registry

  product_service:
    build: ./product_service
    container_name: product_service
    ports:
      - "8002:8002"
    depends_on:
      - registry
